### PR TITLE
Flutter workshop and web hunt changes

### PR DESCRIPTION
**Pull request by libreinator**
Have to change rules and regulations also, as soon as I receive them.

### CODE REVIEW

**Comment by libreinator** [comment]
Added flutter workshop

**Comment by vishalkrishnads** [comment]
Should I merge this now or after you get rules & regulations.

**Comment by libreinator** [comment]
Nobody knows the rules, so youd better do the honours without waiting anymore.On 02-Mar-2024 6:04 pm, Vishal ***@***.***> wrote:
Should I merge this now or after you get rules & regulations.

**Comment by vishalkrishnads** [comment]
okay, as you say

**Pull request merged**
