### PR TITLE
fix names&numbers of coordinators in events.json

### PR DESCRIPTION
**Pull request by libreinator**
Changed guidelines and description for SegFault.
Probably I'll have to come back and edit again 😅

### CODE REVIEW

**Comment by libreinator** [comment]
Please hold on while I'm verifying the stuff one last time

**Comment by vishalkrishnads** [comment]
Hey, could you please change all occurrences of 

```json
"regfee":  "free"
```

to 

```json
"regfee":  "0"
```

The UI will render a `₹` symbol before the registration fee automatically. So, `₹free` would look weird.

**Comment by libreinator** [comment]
Okay, in a minute

**Comment by libreinator** [comment]
I think I'm done

**Comment by libreinator** [comment]
Wait, I forgot to add the quotes in "0", is that a problem?

**Comment by vishalkrishnads** [comment]
Apparently not 😅  status check would've said so

**Pull request merged**
